### PR TITLE
Add helsinkibus

### PR DESCRIPTION
**Pull request by karrika**
I modified your London Bus a bit for the Helsinki area. Actually the same code works in the entire Finland I presume. The queries are created by the GraphQL interface.

Could this be added to your project?

### CODE REVIEW

**Comment by elParaguayo** [comment]
Thanks. 

I have no objections to adding this. I'm very busy at work though so may take me a while to get round to merging it.

**Comment by karrika** [comment]
That is ok. I also plan to add support for alerts at the bottom of the screen. Like canceled buses due to technical problems. So the pull request may change a little. Take your time.

**Comment by karrika** [comment]
Thank you Tuukka. Much appreciated.

**Comment by elParaguayo** [comment]
Screen looks good. Happy to merge if no-one else has any other commits to add here.

**Comment by elParaguayo** [comment]
NB This will be manually merged into a version0.4 pre-release branch as this is the way I tend to check everything before merging into "master" branch.

**Comment by elParaguayo** [comment]
Manually merged into version 0.4

**Pull request closed without merging**
