### PR TITLE
Dutch Word Clock

### PR DESCRIPTION
**Pull request by jorismathijssen**
Word clock for dutch. Changed sized because dutch uses shorter words than English. So it will fit better on the screen

### CODE REVIEW

**Comment by elParaguayo** [comment]
I've just tried this. It's 8:20 but it says "Het is tien voor acht" which Google tells me means "It is ten to eight".
Are you sure this is correct?

**Comment by jorismathijssen** [comment]
I missed something. I Will fix this asap :')

**Comment by jorismathijssen** [comment]
I checked it this time. I did not know how HOUR_INCREMENT_TIME worked. Sorry for the troubles.

**Comment by elParaguayo** [comment]
OK. Are you sure about the number you've used? 15 seems an unusual number.

In English it's "Half past one" and "twenty five to two" for 13:30 and 13:35. When does the hour change in Dutch?

**Comment by jorismathijssen** [comment]
From wikipedia: Half hours are relative to the next hour – for example, 5:30 is said as "half 6". Quarter hours are expressed relative to the nearest whole hour – for example, 6:15, "kwart over 6" (quarter past six) and 6:45, "kwart voor zeven" (quarter to seven). Minutes are usually rounded off to the nearest five minutes and are expressed relative to the closest half-hour. For instance 05:35 is "5 over half 6" (literally "5 past half to 6") and 05:20 is "tien voor half 6" (literally "10 to half to 6").

**Comment by jorismathijssen** [comment]
The last sentence is important. I have the clock running for 3 days now. And i saw almost all the different times.

**Comment by elParaguayo** [comment]
Agreed. The last sentence is the most important.

Your change makes perfect sense now. 

I will try to merge tonight.

**Pull request merged**
